#%RAML 1.0 NamedExample
orders:
value:
  -
    OID: OID10
    PID: PID10
    PName: Pd10
    CID: CID10
    ODt: 2020-12-23T03:15:34
    Quant: 1
    ShipDt: 2020-12-23T03:45:32
    TotalPrice: 10000.00
    PaymentDt: 2020-12-23T03:46:43
    PaymentStat: Success
    ShipAddr: Mumbai, India

  -
    OID: OID11
    PID: PID11
    PName: Pd11
    CID: CID11
    ODt: 2020-12-23T04:15:34
    Quant: 2
    ShipDt: 2020-12-23T04:45:32
    TotalPrice: 100000.00
    PaymentDt: 2020-12-23T04:46:43
    PaymentStat: Success
    ShipAddr: Delhi, India
