#%RAML 1.0 NamedExample
products:
value:
  -
    PId: PD10
    PName: Pd1
    PtDesc: Galaxy Phone
    UnitPrice: 16000.21
    AvailableQuant: 5
  -
    PId: PID2
    PName: Prod2
    PDesc: IPhone
    UnitPrice: 100000.35
    AvailableQuant: 5

  -
    PId: PID3
    PName: Prod3
    PDesc: Moto G6
    UnitPrice: 30000.45
    AvailableQuant: 5