#%RAML 1.0 NamedExample
sendOrder:
value:
    OID: OD10
    PID: PID10
    PName: Samsung
    CID: CD10
    ODate: 2020-12-24T05:30:00
    Quant: 1
    ShipDt: 2020-12-23T07:42:22
    TotPrice: 120000.00
    PaymentDt: 2020-12-24T02:12:42
    PaymentStat: Success
    ShippiAddr:  Mumbai, India